apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  namespace: dev
  labels:
    app: iot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
      - name: iot-app
        image: svvoii/iot-app:v2
        ports:
        - containerPort: 8888
