apiVersion: v1
kind: Service
metadata:
  name: iot-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: iot-app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30080
